spring:
  datasource:
    url: "jdbc:mysql://johnny.heliohost.org:3306/thef4b1_orfapbackend"
    username: "thef4b1_orfap"
    # Set in Heroku
    #password:
    tomcat:
      # Stupid mysql Limit...
      max-active: 4
      max-wait: 10000
  jpa:
    hibernate:
        ddl-auto: update
    database: MYSQL
