spring:
  datasource:
    url: "jdbc:mysql://orfap.heliohost.com:3306/thef4b1_orfapbackend"
    username: "orfap"
# Set in Heroku
#    password:
  jpa:
    hibernate:
        ddl-auto: update
    database: MYSQL
